--- #YAML:1.0
name:                REST-Google-Apps-Provisioning
version:             1.1.1
abstract:            A Perl library to Google's RESTful Apps API 
license:             perl
distribution_type:   module
author:
    - Scott Schneider <sschneid@gmail.com>

